open_science_survey_search.settings:
  type: config_object
  label: 'OpenSearch Analyzer Settings'
  mapping:
    stop_words:
      type: text
      label: 'Stop words (one per line)'
    significant_terms:
      type: mapping
      label: 'Significant Terms Aggregation Settings'
      mapping:
        min_doc_count:
          type: integer
          label: 'Minimum document count'
        shard_size:
          type: integer
          label: 'Shard size'
        size:
          type: integer
          label: 'Maximum number of terms to return'
        max_entries:
          type: integer
          label: 'Maximum number of entries in API response'
        min_weight_percent:
          type: float
          label: 'Minimum percent weight threshold'
